import { PERMISSIONS } from "@/lib/constants";

export const SETTINGS_ACCESS_PERMISSIONS: string[] = [
  PERMISSIONS.API_KEY_READ,
  PERMISSIONS.WEBHOOK_READ,
  PERMISSIONS.SYSTEM_CONFIG_READ,
  PERMISSIONS.MAINTENANCE_READ,
  PERMISSIONS.MAINTENANCE_MANAGE,
  PERMISSIONS.CRON_JOB_READ,
];

export const DASHBOARD_ACCESS_PERMISSIONS: string[] = [
  PERMISSIONS.KEYBOARD_READ,
  PERMISSIONS.CATEGORY_READ,
  PERMISSIONS.COLOR_READ,
  PERMISSIONS.STYLE_READ,
  PERMISSIONS.USER_READ,
  PERMISSIONS.ROLE_READ,
  PERMISSIONS.AUDIT_LOG_READ,
  PERMISSIONS.STUDIO_ACCESS,
  ...SETTINGS_ACCESS_PERMISSIONS,
];

export function canAccessDashboard(permissions: string[] = []) {
  return permissions.includes("*") ||
    permissions.includes("admin:*") ||
    permissions.some((permission) => DASHBOARD_ACCESS_PERMISSIONS.includes(permission));
}
