import type { Language } from "@/lib/i18n";

const copy = {
  vi: {
    nav: { explore: "Khám phá", trending: "Thịnh hành", guide: "Hướng dẫn" },
    common: {
      viewAll: "Xem tất cả",
      loading: "Đang tải...",
      retry: "Thử lại",
      downloads: "lượt tải",
      keyboards: "giao diện",
      previous: "Trang trước",
      next: "Trang sau",
      page: "Trang",
      of: "trên",
    },
    home: {
      badge: "Thư viện theme bàn phím điện thoại cho iOS và Android",
      title: "Mỗi lần gõ, một chút dễ thương",
      description:
        "Xem trước nhiều hình ảnh và tải bộ file theme cho bàn phím điện thoại của bạn.",
      search: "Tìm theo tên giao diện, mô tả...",
      searchAction: "Tìm giao diện",
      trending: "Đang thịnh hành",
      trendingDesc: "Các giao diện có nhiều lượt tải nhất gần đây.",
      discordTitle: "Cùng nhau làm bàn phím đẹp hơn",
      discordDesc: "Tham gia Discord để nhận theme, chia sẻ bàn phím và gặp các creator.",
      discordAction: "Tham gia Discord",
    },
    explore: {
      eyebrow: "Thư viện theme điện thoại",
      title: "Tìm theme bàn phím dành cho bạn",
      description: "Lọc theo phong cách và nền tảng. Mọi lựa chọn đều được lưu trên URL.",
      search: "Tìm theo tên giao diện...",
      category: "Danh mục",
      allCategories: "Tất cả danh mục",
      colors: "Màu sắc",
      styles: "Phong cách",
      allColors: "Tất cả màu sắc",
      allStyles: "Tất cả phong cách",
      selected: "mục đã chọn",
      platform: "Nền tảng",
      allPlatforms: "Mọi nền tảng",
      sort: "Sắp xếp",
      latest: "Mới nhất",
      popular: "Phổ biến nhất",
      liked: "Được yêu thích",
      nameAsc: "Tên A đến Z",
      nameDesc: "Tên Z đến A",
      results: "kết quả phù hợp",
      clear: "Xóa bộ lọc",
      emptyTitle: "Chưa tìm thấy theme phù hợp",
      emptyDesc: "Hãy thử từ khóa ngắn hơn hoặc bỏ bớt một bộ lọc.",
      errorTitle: "Chưa thể tải thư viện",
      errorDesc: "Kết nối đến máy chủ đang gặp sự cố. Vui lòng thử lại.",
    },
    detail: {
      back: "Quay lại thư viện",
      preview: "Ảnh xem trước",
      previewDescription: "Cover và các mockup cho thấy theme hiển thị thực tế trên điện thoại.",
      imageUnit: "hình",
      about: "Về giao diện này",
      platform: "Nền tảng",
      categories: "Danh mục",
      colors: "Màu sắc",
      styles: "Phong cách",
      likes: "Lượt thích",
      liked: "Đã thích",
      likeAction: "Thích theme này",
      unlikeAction: "Bỏ thích theme này",
      likeLogin: "Bạn cần đăng nhập để thích theme.",
      likedSuccess: "Đã thêm theme vào danh sách yêu thích",
      unlikedSuccess: "Đã bỏ thích theme",
      likeError: "Chưa thể cập nhật lượt thích. Vui lòng thử lại.",
      access: "Quyền truy cập",
      creator: "Người sáng tạo",
      related: "Có thể bạn cũng thích",
      relatedDesc: "Những giao diện cùng phong cách để bạn khám phá tiếp.",
      noDescription: "Creator chưa thêm mô tả cho theme này.",
      packageTitle: "Gói file theme",
      packageDescription: "Sau khi xác thực, Loichoi sẽ mở liên kết tải xuống được bảo vệ trên Google Drive hoặc Discord.",
      packageIncludes: "Nhiều file cài đặt và tài nguyên",
    },
    download: {
      action: "Tải bộ file",
      checking: "Đang kiểm tra quyền...",
      success: "Đã mở liên kết tải xuống",
      login: "Bạn cần đăng nhập trước khi tải giao diện.",
      forbidden: "Tài khoản của bạn chưa đủ quyền tải giao diện này.",
      quota: "Bạn đã đạt giới hạn lượt tải cho cấp bậc hiện tại. Hãy tham gia Discord hoặc nâng cấp Server Booster để nhận thêm lượt tải.",
      quotaAction: "Mở khóa thêm lượt tải",
      discordRole: "Giao diện này dành riêng cho thành viên có Role đặc biệt trên máy chủ Discord.",
      missing: "Theme này không còn tồn tại hoặc chưa được phát hành.",
      rate: "Bạn thao tác tải quá nhanh. Vui lòng chờ một phút rồi thử lại.",
      error: "Máy chủ chưa thể xử lý lượt tải. Vui lòng thử lại.",
      loginAction: "Đăng nhập",
      discordAction: "Mở Discord",
    },
    trending: {
      eyebrow: "Được cộng đồng yêu thích",
      title: "Giao diện đang thịnh hành",
      description: "Xếp hạng theo lượt tải để bạn không bỏ lỡ những thiết kế nổi bật.",
    },
    guide: {
      eyebrow: "Cẩm nang hướng dẫn & Hỗ trợ",
      title: "Cách Tải Bàn Phím Dễ Thương",
      description: "Cẩm nang hướng dẫn chi tiết từng bước cài đặt bàn phím siêu cute qua Baidu Keyboard cùng Roi.",
    },
    footer: {
      description: "Thư viện theme bàn phím điện thoại với nhiều ảnh xem trước và bộ file tải cho iOS, Android.",
      discover: "Khám phá",
      community: "Mạng xã hội",
      account: "Tài khoản",
      rights: "Loichoi. Nội dung được bảo lưu.",
    },
  },
  en: {
    nav: { explore: "Explore", trending: "Trending", guide: "Guide" },
    common: {
      viewAll: "View all",
      loading: "Loading...",
      retry: "Try again",
      downloads: "downloads",
      keyboards: "themes",
      previous: "Previous",
      next: "Next",
      page: "Page",
      of: "of",
    },
    home: {
      badge: "Mobile keyboard theme library for iOS and Android",
      title: "A little joy in every keystroke",
      description:
        "Browse rich previews and download theme packs for your mobile keyboard.",
      search: "Search by theme name, description...",
      searchAction: "Find themes",
      trending: "Trending now",
      trendingDesc: "The most downloaded themes in the library.",
      discordTitle: "Let's make keyboards beautiful together",
      discordDesc: "Join Discord for community themes, keyboard screenshots, and creator conversations.",
      discordAction: "Join Discord",
    },
    explore: {
      eyebrow: "Mobile theme library",
      title: "Find a keyboard theme made for you",
      description: "Filter by style and platform. Every choice stays in the URL.",
      search: "Search theme names...",
      category: "Category",
      allCategories: "All categories",
      colors: "Colors",
      styles: "Styles",
      allColors: "All colors",
      allStyles: "All styles",
      selected: "selected",
      platform: "Platform",
      allPlatforms: "All platforms",
      sort: "Sort by",
      latest: "Newest",
      popular: "Most popular",
      liked: "Most liked",
      nameAsc: "Name A to Z",
      nameDesc: "Name Z to A",
      results: "matching results",
      clear: "Clear filters",
      emptyTitle: "No matching themes yet",
      emptyDesc: "Try a shorter search or remove one of the filters.",
      errorTitle: "The library could not load",
      errorDesc: "The server connection is having trouble. Please try again.",
    },
    detail: {
      back: "Back to library",
      preview: "Preview images",
      previewDescription: "Cover art and mockups show how this theme looks on a real phone.",
      imageUnit: "images",
      about: "About this theme",
      platform: "Platform",
      categories: "Categories",
      colors: "Colors",
      styles: "Styles",
      likes: "Likes",
      liked: "Liked",
      likeAction: "Like this theme",
      unlikeAction: "Unlike this theme",
      likeLogin: "Please sign in to like this theme.",
      likedSuccess: "Theme added to your favorites",
      unlikedSuccess: "Theme removed from your favorites",
      likeError: "The like could not be updated. Please try again.",
      access: "Access",
      creator: "Creator",
      related: "You may also like",
      relatedDesc: "More themes with a similar style to continue exploring.",
      noDescription: "The creator has not added a description yet.",
      packageTitle: "Theme file pack",
      packageDescription: "After authorization, Loichoi opens the protected Google Drive or Discord download link.",
      packageIncludes: "Multiple installation files and assets",
    },
    download: {
      action: "Download file pack",
      checking: "Checking access...",
      success: "Your download link is opening",
      login: "Please sign in before downloading this theme.",
      forbidden: "Your account does not have access to this theme yet.",
      quota: "You have reached your download quota for your current tier. Join our Discord or boost the server to unlock more downloads.",
      quotaAction: "Unlock more downloads",
      discordRole: "This theme is reserved for members with a special Discord role.",
      missing: "This theme no longer exists or is not published.",
      rate: "There have been too many download requests. Please wait a minute and try again.",
      error: "The server could not process this download. Please try again.",
      loginAction: "Sign in",
      discordAction: "Open Discord",
    },
    trending: {
      eyebrow: "Loved by the community",
      title: "Themes trending now",
      description: "Ranked by downloads so you never miss a standout design.",
    },
    guide: {
      eyebrow: "User Guide & Support",
      title: "How to Get Free Cute Keyboards",
      description: "A complete step-by-step tutorial on setting up cute kawaii keyboards via Baidu Keyboard with Roi.",
    },
    footer: {
      description: "Mobile keyboard themes with rich previews and downloadable file packs for iOS and Android.",
      discover: "Discover",
      community: "Socials",
      account: "Account",
      rights: "Loichoi. All content reserved.",
    },
  },
} as const;

export function getPublicCopy(language: Language) {
  return copy[language];
}

